main: fr.thebrian22950.pc.Plugin
name: PortableCraft
version: 0.1
author: Brian22950
commands:
  portableworkbench:
    description: Un etabli portable.
    usage: "/<command>"
    permission: "portablecraft.pw"
    aliases: ["pw"]
  portableenchant:
    description: Une table d'enchantement portable.
    usage: "/<command>"
    permission: "portablecraft.pe"
    aliases: ["pe"]
 
permissions:
    portablecraft.pw:
        default: op
    portablecraft.pe:
        default: op
        
